# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
    - main

variables:
- group: 'VarGroup'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: GitHub
  displayName: Update GitHub repo
  jobs:
    - job: GitHub
      steps:
        - task: PowerShell@2
          displayName: Mirror Azure Devop repo
          inputs:
            targetType: 'inline'
            script: |
              # Clone the original repository as a bare mirror
              $sourceURL = ("https://{0}@dev.azure.com/juangarridocaballero/publicmonkey/_git/test" -f ${env:token})
              Write-Output '*****Mirroring local repository****'
              git clone --mirror $sourceURL ${env:output}
              # Navigate to the bare clone directory
              Write-Output '*****Successfully cloned repository****'
          env:
            token: $(System.AccessToken)
            pat: $(GitHubPat)
            username: $(Build.RequestedFor)
            email: $(Build.RequestedForEmail)
            source: $(Build.Repository.Uri)
            output: $(Build.ArtifactStagingDirectory)\newfolder
            desturl: silverhack/testdevops
        - task: PipAuthenticate@1
          displayName: 'Pip Authenticate'
          # Use command line tool to 'pip install'.
        - script: |
            pip install --upgrade pip setuptools wheel git-filter-repo
        - task: Bash@3
          displayName: Remove pipeline data
          inputs:
            scriptSource: 'inline'
            script: |
              ls -la
              git git-filter-repo --path "Pipeline/azure-pipelines.yml" --invert-paths
            workingDirectory: '$(Build.ArtifactStagingDirectory)/newfolder'
        - task: PowerShell@2
          displayName: Update GitHub repo
          inputs:
            targetType: 'inline'
            script: |
              #set GitHub url 
              $newOrigin = ("https://{0}@github.com/{1}.git" -f ${env:pat}, ${env:desturl})
              Set-Location ${env:output}
              # Set your personal GitHub repo as the push destination
              git remote add --mirror=fetch secondary $newOrigin
              # To update the mirror in the future
              git pull ("https://github.com/{0}.git" -f ${env:desturl})
              git remote prune ${env:source}
              Write-Output '*****Git fetch origin****'
              git fetch ${env:source}
              Write-Output '*****Git push secondary****'
              git push secondary --all -f
              Write-Output '**Azure Devops repo synced with Github repo**'
          env:
            token: $(System.AccessToken)
            pat: $(GitHubPat)
            username: $(Build.RequestedFor)
            email: $(Build.RequestedForEmail)
            source: $(Build.Repository.Uri)
            output: $(Build.ArtifactStagingDirectory)\newfolder
            desturl: silverhack/testdevops
            
              