# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
    - main

variables:
- group: 'VarGroup'

pool:
  vmImage: windows-latest

stages:
- stage: GitHub
  displayName: Update GitHub repo
  jobs:
    - job: GitHub
      steps:
        - task: PowerShell@2
          displayName: Update GitHub repo
          inputs:
            targetType: 'inline'
            script: |
              write-host $(Pipeline.Workspace)
              write-host ${env:source}
              #set GitHub url 
              $newOrigin = ('https://{0}@{1}' -f ${env:pat},${env:desturl})
              # Clone the original repository as a bare mirror
              git clone --mirror -c http.extraheader="Authorization: Bearer ${env:token}" ${env:source} ${env:dest}
              # Navigate to the bare clone directory
              write-host "cloned!!!"
              Set-Location ${env:dest}
              # Set your personal GitHub repo as the push destination
              git remote add --mirror=fetch secondary $newOrigin
              # To update the mirror in the future
              git remote -v
              git pull https://github.com/silverhack/testdevops.git
              git remote prune ${env:source}
              Write-Output '*****Git fetch origin****'
              git fetch ${env:source}
              Write-Output '*****Git push secondary****'
              git push secondary --all -f
              Write-Output '**Azure Devops repo synced with Github repo**'
          env:
            token: $(System.AccessToken)
            pat: $(GitHubPat)
            username: $(Build.RequestedFor)
            email: $(Build.RequestedForEmail)
            source: $(Build.Repository.Uri)
            dest: newfolder
            desturl: github.com/silverhack/testdevops.git