# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
    - main

variables:
- group: 'VarGroup'

pool:
  vmImage: windows-latest

stages:
- stage: GitHub
  displayName: Update GitHub repo
  jobs:
    - job: GitHub
      steps:
        - task: PowerShell@2
          displayName: Update GitHub repo
          inputs:
            targetType: 'inline'
            script: |
              #Skip pipeline
              cd $(System.DefaultWorkingDirectory)
              #git filter-branch --index-filter 'git rm -rf --cached --ignore-unmatch Pipeline/azure-pipelines.yml' HEAD
              #git push origin main
              #set GitHub url 
              $newOrigin = ("https://{0}@github.com/{1}.git" -f ${env:pat}, ${env:desturl})
              # Clone the original repository as a bare mirror
              $sourceURL = ("https://{0}@dev.azure.com/juangarridocaballero/publicmonkey/_git/test" -f ${env:token})
              Write-Output '*****Mirroring local repository****'
              git clone --mirror $sourceURL ${env:dest}
              # Navigate to the bare clone directory
              Write-Output '*****Successfully cloned repository****'
              Set-Location ${env:dest}
              # Set your personal GitHub repo as the push destination
              git remote add --mirror=fetch secondary $newOrigin
              # To update the mirror in the future
              git pull ("https://github.com/{0}.git" -f ${env:desturl})
              git remote prune ${env:source}
              Write-Output '*****Git fetch origin****'
              git fetch ${env:source}
              Write-Output '*****Git push secondary****'
              git push secondary --all -f
              Write-Output '**Azure Devops repo synced with Github repo**'
          env:
            token: $(System.AccessToken)
            pat: $(GitHubPat)
            username: $(Build.RequestedFor)
            email: $(Build.RequestedForEmail)
            source: $(Build.Repository.Uri)
            dest: newfolder
            desturl: silverhack/testdevops