name: Create Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10	  
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d_%H%M%S')" >> $GITHUB_OUTPUT
      - name: Set release
        id: release_message
        run: |
          echo "message=Thanks for follow [Monkey365](https://github.com/silverhack/monkey365)! This is a tagged release (${{ steps.date.outputs.today }})." >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.date.outputs.today }}
          release_name: Release ${{ steps.date.outputs.today }}
          body: ${{ env.message }}
          draft: false
          prerelease: false
      # Create a zip of the folder
      - name: Create ZIP file of the folder
        if: steps.create_release.outcome  == 'success'
        run: |
          mkdir -p build
          git archive --format zip --output ./build/assets.zip main
          gh release upload ${{ steps.date.outputs.today }} ./build/assets.zip
          sha256sum ./build/assets.zip | awk '{print $1}' > ./build/assets.sha256
          gh release upload ${{ steps.date.outputs.today }} ./build/assets.sha256
          sha512sum ./build/assets.zip | awk '{print $1}' > ./build/assets.sha512
          gh release upload ${{ steps.date.outputs.today }} ./build/assets.sha512
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}