name: Test 1

on:
  push:
    branches:
      - main
env:
  BADGE_MESSAGE: ${{ github.event.commits[0].message }}

jobs:
  create-badge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "It works"