name: Test 1

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10  
env:
  BADGE_MESSAGE: ${{ github.event.commits[0].message }}

jobs:
  create-badge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "It works"